### ISSUE TITLE
can not getting expected results in example

### ISSUE THREAD

**Issue by kuzen** [PRBonn/rangenet_lib#30] opened 2020-06-09 07:02 UTC
this is my result
![image](https://user-images.githubusercontent.com/16202160/84116269-12f84980-aa62-11ea-9e79-e7205819bd5e.png)

**Comment by Chen-Xieyuanli** [comment] 2020-06-10 06:39
Hey @kuzen, this problem usually caused by incompatible versions of tensorrt or graphic card related drivers. Could you please have a check at the similar issue #9. 

To keep tracking similar problems in one issue, I would like to close this one. Please feel free to ask me to reopen this issue if needed.

**Closed by Chen-Xieyuanli** 2020-06-10 06:39 UTC
